name: Deploy notes-api-demo

on:
  push:
    branches:
      - main

jobs:
  DevelopmentDeployment:
    name: development deployment
    runs-on: ubuntu-latest
    environment:
      name: Deployment
      url: https://test.com
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v2
        with:
          args: -c "serverless plugin install --name serverless-iam-roles-per-function && serverless deploy --stage dev"
          entrypoint: /bin/sh
