name: Deploy notes-api-demo

on:
  push:
    branches:
      - main

jobs:
  DevelopmentDeployment:
    name: development deployment
    runs-on: ubuntu-latest
    environment:
      name: Deployment
      url: https://test.com
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Plugin and Deploy
        run: |
          npm install -g serverless
          serverless plugin install --name serverless-iam-roles-per-function
          serverless deploy --stage dev
